### ISSUE TITLE
Pronoun set ordering & reasons

### ISSUE THREAD

**Issue by pedantic-git** [fishpercolator/name.pn#13]
Although name.pn allows people to select multiple pronoun sets, these are always shown in a fixed order (e.g. they/them first).

I'd like to be able to allow users to specify the order they want their pronouns to appear on their profile, as well as "reasons" - e.g. what contexts those pronouns are used in.

Since I only have one set of pronouns myself, I feel slightly ill-equipped to implement this feature sensitively, and would appreciate thoughts in this thread from people who use multiple pronouns about how to provide the best user experience.

**Comment by pedantic-git** [comment]
@iMartyn Thank you for this personal view. I've also been collecting views on this subject on my personal Twitter because it's one I'd like to get right in a future release!

At the moment I'm thinking as a first option we should allow people to order their pronouns, and then maybe later add the reasons/circumstances as an optional field to each set of pronouns.

**Comment by iMartyn** [comment]
Sounds great to me, glad to have contributed to the discussion.

**Comment by caseywatts** [comment]
Thank you for [pinging me on Twitter](https://twitter.com/fishpercolator/status/1472190835466936322?s=20)! :D
I do have a lot of thoughts about how to convey pronoun priority :)

Persona 1, Someone with a name.pn porfile. For me and also for people I've talked to, these are the two things people most often want others to understand about us:
* "these pronoun(s) are okay to use with me" (yes to these, no to others)
* "I do/don't have a preference between these"

Persona 2, Someone reading name.pn. This is what people consuming this information often want to know:
* "What single pronoun should I use with this person?"
  * If someone only has one set of pronouns, done!
  * If someone has two approved pronouns, and has a preference between them, we can answer with the preference, great!
  * If someone has two approved pronouns, and has no preference between them, truly tied, that's okay and this person seeking one pronoun to use can deal with that, they just need to be reassured that it's truly/practically tied.
* "If I make a mistake using the wrong pronoun, how did I make the person feel?" Many people lately are good about assuming a pronoun mistake is harmful, but it's not always harmful and that's interesting/helpful to know too. For some people (even queer/trans people!) it's not harmful at all to them personally. This can come out when navigating how to recover (which is super important!).  (also btw since this is The Internet: I realize that a better guideline generally is to just move on past it, but sometimes people do have reason to apologize/repair explicitly, like in closer relationships)
  * For someone who does feel hurt by the wrong pronouns, someone apologizing could include "I know this is important to you, I'll do better."
  * For someone who doesn't feel hurt at all, someone apologizing saying "I know this is important to you" is wrong lol. They could instead say something along the lines of "I know you don't mind as much as many people do, thank you for being patient with me as I learn." or maybe they don't have to say something quite like that at all.

--- 

Here's another way I've said the same sort of ideas, and a graphic I use

Here's how I think about it for myself:
![image](https://user-images.githubusercontent.com/273653/146644821-a2f2c4e1-cfe8-4f67-a0c9-e2d39f4149e2.png)

This diagram shows a lot of nuance:
* Use he/him pronouns for me
* Please don’t use she/her on me, I don’t like that.
* They/them is fine I guess, but since I prefer he/him, please use that instead.

When you get someone’s pronouns wrong
* for some people it doesn’t hurt at all (like straight men who don’t get it lol)
* for some people it does hurt a lot

What about people with two pronouns in their profile? Like she/they
* Both are okay! They said so :white_check_mark:
* They may have a slight preference between them, you can ask if they do. They also might not have any preference between them.

---

Someone from a Slack I'm on loves the idea of displaying this on a scale/graphic like this! They immediately jumped on the idea and even said, in their first comment, that they hope name.pn could get this sort of feature. 

Numbers/scales vs Text.
I like the scales version a lot myself as a self-descriptive tool, but we could meet a lot of the goals of "how to interact with each other" with a drop-down sort of thing with text, it doesn't have to be a numbers scale to have the effect.

**Comment by pedantic-git** [comment]
@caseywatts Thank you so much for this detailed additional context!! It gives me lots of ideas about what to implement next!

name.pn is a labour of love for me personally and so it will take a long time (years, probably) to get to capture all this nuance but I really do want to get there one day! It feels like your thoughts have given me ideas about how to prioritize.

Myself, there's only one set of pronouns that actively _hurts_ and it's the set people who have never met me are most likely to use for me. All the others apart from they/them (the pronouns I use for myself) don't hurt but they do feel wrong.

**Comment by caseywatts** [comment]
Happy to help! I’m a fan of name.pn 😄

here’s an even more nuanced image from someone on a Slack I’m on (shared with permission)
![0EC6F5AE-FF56-42A6-AEA9-3E01639B2704](https://user-images.githubusercontent.com/273653/146794315-42bd11b8-3636-4b03-ad2d-faca9b086a23.jpeg)

and their description of the axes:
frequency = how often I feel this particular response to being called this pronoun
intensity = how strongly I feel the response

**Comment by erbridge** [comment]
I would really like this feature (and would be willing to do the legwork to implement it if that would be welcome). For me, specifically, just being able to choose a custom order would be enough, and I imagine that would be true of most people. It might then make sense to add some of these other features.

I see this as "What order would you like your pronouns to appear on the page?" rather than "Do you have a preference between pronouns?" or similar. The former is functional without interpreting intent behind the choice, and feels like a direct upgrade for people in every case.

**Comment by pedantic-git** [comment]
@erbridge I really appreciate your thoughts on this, and also your offer to contribute code - I might take you up on that! I'll move this into the "Beta" milestone as a priority need (at least the ordering part) and try to get to work on it in the near future.

My current thinking for implementation is an old-school "pick and reorder" widget that only appears if the user clicks an "Advanced" button on the page (I'm trying to make sure in the common case it's accessible - e.g. with usage examples - for people who are less familiar with pronoun usage).

![pronouns_advanced](https://user-images.githubusercontent.com/962930/191479867-780843b7-47de-4c6f-95f7-f1c9dae727c5.png)

I've no idea how to make this kind of UI work in a progressive disclosure kind of way without JS (maybe having little text boxes for numeric indexes?) Any existing libraries or patterns you're aware of would be *greatly* appreciated!

**Comment by erbridge** [comment]
I'd suggest checkboxes for in vs out combined with numeric ordering and validation of that ordering on submission. You can then make the fancy widget set those values on invisible input fields under the hood and submit the form when it's done.

**Comment by pedantic-git** [comment]
Looks like [SortableJS](https://sortablejs.github.io/Sortable/) is the go-to library for this purpose, and it looks like I could use it to progressively enhance a form with numeric indexes. I'll probably play around a few days before there's any code to share.

**Comment by pedantic-git** [comment]
This first part is implemented and deployed to production now. The UI turned out to be "just the old UI but with drag-and-drop". I think it works OK even if it's not immediately obvious you can do it (unless you read the accompanying text).

I'm especially interested in your thoughts @erbridge & @caseywatts, and also @erbridge if you would still like to help code-wise I'm a bit [stuck on automating it](https://github.com/fishpercolator/name.pn/blob/main/features/signup_and_edit_profile.feature#L242) - the cuprite driver only recently added support for drag-and-drop and it doesn't seem to work. Driving this test another way (using another driver or some sort of sneaky back door) might be the solution. I'm also going to revive the conversation on the cuprite issue itself.

**Comment by pedantic-git** [comment]
I'm going to reopen the second half of this as a new issue so we can move this one to done.
